import fs from 'fs';
import path from 'path';

const fixturesPath = path.join(process.cwd(), 'src', 'data', 'fixtures.json');

const newFixtures = [
  // Premier League 2024-2025 New Matches (30 matches)
  {
    id: "pl11",
    homeTeam: "Chelsea",
    awayTeam: "Chelsea", // Thêm trận khác Chelsea vs Crystal Palace
    homeTeamName: "Chelsea",
    awayTeamName: "Crystal Palace", // Sửa tên chuẩn bên dưới
    homeTeam: "Chelsea",
    awayTeam: "Crystal Palace",
    date: "2024-09-01",
    time: "13:30",
    group: "Matchday 3",
    venue: "Stamford Bridge, London",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -0.75,
    actualHomeScore: 1,
    actualAwayScore: 1,
    actualCorners: 11,
    actualCards: 5
  },
  {
    id: "pl12",
    homeTeam: "Newcastle",
    awayTeam: "Tottenham",
    date: "2024-09-01",
    time: "13:30",
    group: "Matchday 3",
    venue: "St James' Park, Newcastle",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: 0.25,
    actualHomeScore: 2,
    awayTeam: "Tottenham",
    actualHomeScore: 2,
    actualAwayScore: 1,
    actualCorners: 12,
    actualCards: 6
  },
  {
    id: "pl13",
    homeTeam: "Aston Villa",
    awayTeam: "Everton",
    date: "2024-09-14",
    time: "17:30",
    group: "Matchday 4",
    venue: "Villa Park, Birmingham",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -1.0,
    actualHomeScore: 3,
    actualAwayScore: 2,
    actualCorners: 9,
    actualCards: 4
  },
  {
    id: "pl14",
    homeTeam: "Liverpool",
    awayTeam: "Nottingham Forest",
    date: "2024-09-14",
    time: "15:00",
    group: "Matchday 4",
    venue: "Anfield, Liverpool",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -1.75,
    actualHomeScore: 0,
    actualAwayScore: 1,
    actualCorners: 10,
    actualCards: 3
  },
  {
    id: "pl15",
    homeTeam: "Tottenham",
    awayTeam: "Brentford",
    date: "2024-09-21",
    time: "15:00",
    group: "Matchday 5",
    venue: "Tottenham Hotspur Stadium, London",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -1.25,
    actualHomeScore: 3,
    actualAwayScore: 1,
    actualCorners: 11,
    actualCards: 4
  },
  {
    id: "pl16",
    homeTeam: "Crystal Palace",
    awayTeam: "Manchester United",
    date: "2024-09-21",
    time: "17:30",
    group: "Matchday 5",
    venue: "Selhurst Park, London",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: 0.25,
    actualHomeScore: 0,
    actualAwayScore: 0,
    actualCorners: 8,
    actualCards: 5
  },
  {
    id: "pl17",
    homeTeam: "Newcastle",
    awayTeam: "Manchester City",
    date: "2024-09-28",
    time: "12:30",
    group: "Matchday 6",
    venue: "St James' Park, Newcastle",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: 0.75,
    actualHomeScore: 1,
    actualAwayScore: 1,
    actualCorners: 12,
    actualCards: 6
  },
  {
    id: "pl18",
    homeTeam: "Wolverhampton",
    awayTeam: "Liverpool",
    date: "2024-09-28",
    time: "17:30",
    group: "Matchday 6",
    venue: "Molineux Stadium, Wolverhampton",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: 1.5,
    actualHomeScore: 1,
    actualAwayScore: 2,
    actualCorners: 9,
    actualCards: 4
  },
  {
    id: "pl19",
    homeTeam: "Manchester United",
    awayTeam: "Tottenham",
    date: "2024-09-29",
    time: "16:30",
    group: "Matchday 6",
    venue: "Old Trafford, Manchester",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -0.25,
    actualHomeScore: 0,
    actualAwayScore: 3,
    actualCorners: 10,
    actualCards: 6
  },
  {
    id: "pl20",
    homeTeam: "Arsenal",
    awayTeam: "Southampton",
    date: "2024-10-05",
    time: "15:00",
    group: "Matchday 7",
    venue: "Emirates Stadium, London",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -2.25,
    actualHomeScore: 3,
    actualAwayScore: 1,
    actualCorners: 13,
    actualCards: 3
  },
  {
    id: "pl21",
    homeTeam: "Manchester City",
    awayTeam: "Fulham",
    date: "2024-10-05",
    time: "15:00",
    group: "Matchday 7",
    venue: "Etihad Stadium, Manchester",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -1.75,
    actualHomeScore: 3,
    actualAwayScore: 2,
    actualCorners: 11,
    actualCards: 2
  },
  {
    id: "pl22",
    homeTeam: "Chelsea",
    awayTeam: "Nottingham Forest",
    date: "2024-10-06",
    time: "14:00",
    group: "Matchday 7",
    venue: "Stamford Bridge, London",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -1.0,
    actualHomeScore: 1,
    actualAwayScore: 1,
    actualCorners: 12,
    actualCards: 5
  },
  {
    id: "pl23",
    homeTeam: "Bournemouth",
    awayTeam: "Arsenal",
    date: "2024-10-19",
    time: "17:30",
    group: "Matchday 8",
    venue: "Vitality Stadium, Bournemouth",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: 1.0,
    actualHomeScore: 2,
    actualAwayScore: 0,
    actualCorners: 10,
    actualCards: 4
  },
  {
    id: "pl24",
    homeTeam: "Wolverhampton",
    awayTeam: "Manchester City",
    date: "2024-10-20",
    time: "14:00",
    group: "Matchday 8",
    venue: "Molineux Stadium, Wolverhampton",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: 1.5,
    actualHomeScore: 1,
    actualAwayScore: 2,
    actualCorners: 11,
    actualCards: 3
  },
  {
    id: "pl25",
    homeTeam: "Chelsea",
    awayTeam: "Newcastle",
    date: "2024-10-27",
    time: "14:00",
    group: "Matchday 9",
    venue: "Stamford Bridge, London",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -0.5,
    actualHomeScore: 2,
    actualAwayScore: 1,
    actualCorners: 10,
    actualCards: 5
  },
  {
    id: "pl26",
    homeTeam: "West Ham",
    awayTeam: "Manchester United",
    date: "2024-10-27",
    time: "14:00",
    group: "Matchday 9",
    venue: "London Stadium, London",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: 0.25,
    actualHomeScore: 2,
    actualAwayScore: 1,
    actualCorners: 8,
    actualCards: 4
  },
  {
    id: "pl27",
    homeTeam: "Newcastle",
    awayTeam: "Arsenal",
    date: "2024-11-02",
    time: "12:30",
    group: "Matchday 10",
    venue: "St James' Park, Newcastle",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: 0.5,
    actualHomeScore: 1,
    actualAwayScore: 0,
    actualCorners: 9,
    actualCards: 5
  },
  {
    id: "pl28",
    homeTeam: "Liverpool",
    awayTeam: "Brighton",
    date: "2024-11-02",
    time: "15:00",
    group: "Matchday 10",
    venue: "Anfield, Liverpool",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -1.25,
    actualHomeScore: 2,
    actualAwayScore: 1,
    actualCorners: 10,
    actualCards: 3
  },
  {
    id: "pl29",
    homeTeam: "Bournemouth",
    awayTeam: "Manchester City",
    date: "2024-11-02",
    time: "15:00",
    group: "Matchday 10",
    venue: "Vitality Stadium, Bournemouth",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: 1.0,
    actualHomeScore: 2,
    actualAwayScore: 1,
    actualCorners: 11,
    actualCards: 4
  },
  {
    id: "pl30",
    homeTeam: "Tottenham",
    awayTeam: "Aston Villa",
    date: "2024-11-03",
    time: "14:00",
    group: "Matchday 10",
    venue: "Tottenham Hotspur Stadium, London",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -0.25,
    actualHomeScore: 4,
    actualAwayScore: 1,
    actualCorners: 12,
    actualCards: 5
  },
  {
    id: "pl31",
    homeTeam: "Manchester United",
    awayTeam: "Leicester City",
    date: "2024-11-10",
    time: "14:00",
    group: "Matchday 11",
    venue: "Old Trafford, Manchester",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -1.0,
    actualHomeScore: 3,
    actualAwayScore: 0,
    actualCorners: 10,
    actualCards: 2
  },
  {
    id: "pl32",
    homeTeam: "Leicester City",
    awayTeam: "Chelsea",
    date: "2024-11-23",
    time: "12:30",
    group: "Matchday 12",
    venue: "King Power Stadium, Leicester",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: 0.75,
    actualHomeScore: 1,
    actualAwayScore: 2,
    actualCorners: 9,
    actualCards: 4
  },
  {
    id: "pl33",
    homeTeam: "Arsenal",
    awayTeam: "Nottingham Forest",
    date: "2024-11-23",
    time: "15:00",
    group: "Matchday 12",
    venue: "Emirates Stadium, London",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -1.5,
    actualHomeScore: 3,
    actualAwayScore: 0,
    actualCorners: 11,
    actualCards: 3
  },
  {
    id: "pl34",
    homeTeam: "Manchester City",
    awayTeam: "Tottenham",
    date: "2024-11-23",
    time: "17:30",
    group: "Matchday 12",
    venue: "Etihad Stadium, Manchester",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -1.25,
    actualHomeScore: 0,
    actualAwayScore: 4,
    actualCorners: 13,
    actualCards: 5
  },
  {
    id: "pl35",
    homeTeam: "Ipswich Town",
    awayTeam: "Manchester United",
    date: "2024-11-24",
    time: "16:30",
    group: "Matchday 12",
    venue: "Portman Road, Ipswich",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: 0.75,
    actualHomeScore: 1,
    actualAwayScore: 1,
    actualCorners: 9,
    actualCards: 4
  },
  {
    id: "pl36",
    homeTeam: "West Ham",
    awayTeam: "Arsenal",
    date: "2024-11-30",
    time: "17:30",
    group: "Matchday 13",
    venue: "London Stadium, London",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: 1.0,
    actualHomeScore: 2,
    actualAwayScore: 5,
    actualCorners: 10,
    actualCards: 5
  },
  {
    id: "pl37",
    homeTeam: "Chelsea",
    awayTeam: "Aston Villa",
    date: "2024-12-01",
    time: "13:30",
    group: "Matchday 13",
    venue: "Stamford Bridge, London",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -0.5,
    actualHomeScore: 3,
    actualAwayScore: 0,
    actualCorners: 11,
    actualCards: 4
  },
  {
    id: "pl38",
    homeTeam: "Liverpool",
    awayTeam: "Manchester City",
    date: "2024-12-01",
    time: "16:00",
    group: "Matchday 13",
    venue: "Anfield, Liverpool",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -0.25,
    actualHomeScore: 2,
    actualAwayScore: 0,
    actualCorners: 12,
    actualCards: 6
  },
  {
    id: "pl39",
    homeTeam: "Arsenal",
    awayTeam: "Manchester United",
    date: "2024-12-04",
    time: "20:15",
    group: "Matchday 14",
    venue: "Emirates Stadium, London",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -0.75,
    actualHomeScore: 2,
    actualAwayScore: 0,
    actualCorners: 10,
    actualCards: 5
  },
  {
    id: "pl40",
    homeTeam: "Everton",
    awayTeam: "Liverpool",
    date: "2024-12-07",
    time: "12:30",
    group: "Matchday 15",
    venue: "Goodison Park, Liverpool",
    tournament: "Premier League",
    season: "2024-2025",
    isTest: true,
    marketHandicap: 1.0,
    actualHomeScore: 0,
    actualAwayScore: 0,
    actualCorners: 8,
    actualCards: 4
  },

  // La Liga 2024-2025 New Matches (20 matches)
  {
    id: "ll11",
    homeTeam: "Athletic Bilbao",
    awayTeam: "Getafe",
    date: "2024-08-15",
    time: "19:00",
    group: "Matchday 1",
    venue: "San Mames, Bilbao",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -0.75,
    actualHomeScore: 1,
    actualAwayScore: 1,
    actualCorners: 8,
    actualCards: 4
  },
  {
    id: "ll12",
    homeTeam: "Real Betis",
    awayTeam: "Girona",
    date: "2024-08-15",
    time: "21:30",
    group: "Matchday 1",
    venue: "Benito Villamarin, Seville",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -0.25,
    actualHomeScore: 1,
    actualAwayScore: 1,
    actualCorners: 9,
    actualCards: 5
  },
  {
    id: "ll13",
    homeTeam: "Real Sociedad",
    awayTeam: "Girona", // Sửa lại một trận khác không trùng
    homeTeam: "Barcelona",
    awayTeam: "Athletic Bilbao", // Dùng trận khác: Girona vs Osasuna
    homeTeam: "Girona",
    awayTeam: "Osasuna",
    date: "2024-08-29",
    time: "19:00",
    group: "Matchday 3",
    venue: "Montilivi, Girona",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -0.75,
    actualHomeScore: 4,
    actualAwayScore: 0,
    actualCorners: 10,
    actualCards: 2
  },
  {
    id: "ll14",
    homeTeam: "Real Madrid",
    awayTeam: "Real Betis",
    date: "2024-09-01",
    time: "21:30",
    group: "Matchday 4",
    venue: "Santiago Bernabeu, Madrid",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -1.5,
    actualHomeScore: 2,
    actualAwayScore: 0,
    actualCorners: 11,
    actualCards: 3
  },
  {
    id: "ll15",
    homeTeam: "Atletico Madrid",
    awayTeam: "Valencia",
    date: "2024-09-15",
    time: "21:00",
    group: "Matchday 5",
    venue: "Metropolitano Stadium, Madrid",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -1.25,
    actualHomeScore: 3,
    actualAwayScore: 0,
    actualCorners: 10,
    actualCards: 4
  },
  {
    id: "ll16",
    homeTeam: "Real Madrid",
    awayTeam: "Espanyol",
    date: "2024-09-21",
    time: "21:00",
    group: "Matchday 6",
    venue: "Santiago Bernabeu, Madrid",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -2.0,
    actualHomeScore: 4,
    actualAwayScore: 1,
    actualCorners: 13,
    actualCards: 3
  },
  {
    id: "ll17",
    homeTeam: "Barcelona",
    awayTeam: "Getafe",
    date: "2024-09-25",
    time: "21:00",
    group: "Matchday 7",
    venue: "Estadi Olimpic Lluis Companys, Barcelona",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -1.75,
    actualHomeScore: 1,
    actualAwayScore: 0,
    actualCorners: 12,
    actualCards: 3
  },
  {
    id: "ll18",
    homeTeam: "Barcelona",
    awayTeam: "Sevilla",
    date: "2024-10-20",
    time: "21:00",
    group: "Matchday 10",
    venue: "Estadi Olimpic Lluis Companys, Barcelona",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -1.5,
    actualHomeScore: 5,
    actualAwayScore: 1,
    actualCorners: 10,
    actualCards: 2
  },
  {
    id: "ll19",
    homeTeam: "Atletico Madrid",
    awayTeam: "Leganes",
    date: "2024-10-20",
    time: "16:15",
    group: "Matchday 10",
    venue: "Metropolitano Stadium, Madrid",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -1.25,
    actualHomeScore: 3,
    actualAwayScore: 1,
    actualCorners: 11,
    actualCards: 4
  },
  {
    id: "ll20",
    homeTeam: "Real Madrid",
    awayTeam: "Osasuna",
    date: "2024-11-09",
    time: "14:00",
    group: "Matchday 13",
    venue: "Santiago Bernabeu, Madrid",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -1.5,
    actualHomeScore: 4,
    actualAwayScore: 0,
    actualCorners: 12,
    actualCards: 2
  },
  {
    id: "ll21",
    homeTeam: "Barcelona",
    awayTeam: "Las Palmas",
    date: "2024-11-30",
    time: "14:00",
    group: "Matchday 15",
    venue: "Estadi Olimpic Lluis Companys, Barcelona",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -2.0,
    actualHomeScore: 1,
    actualAwayScore: 2,
    actualCorners: 11,
    actualCards: 3
  },
  {
    id: "ll22",
    homeTeam: "Real Madrid",
    awayTeam: "Getafe",
    date: "2024-12-01",
    time: "16:15",
    group: "Matchday 15",
    venue: "Santiago Bernabeu, Madrid",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -1.5,
    actualHomeScore: 2,
    actualAwayScore: 0,
    actualCorners: 9,
    actualCards: 4
  },
  {
    id: "ll23",
    homeTeam: "Real Betis",
    awayTeam: "Barcelona",
    date: "2024-12-07",
    time: "16:15",
    group: "Matchday 16",
    venue: "Benito Villamarin, Seville",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: 0.75,
    actualHomeScore: 2,
    actualAwayScore: 2,
    actualCorners: 8,
    actualCards: 5
  },
  {
    id: "ll24",
    homeTeam: "Girona",
    awayTeam: "Real Madrid",
    date: "2024-12-07",
    time: "21:00",
    group: "Matchday 16",
    venue: "Montilivi, Girona",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: 0.5,
    actualHomeScore: 0,
    actualAwayScore: 3,
    actualCorners: 9,
    actualCards: 6
  },
  {
    id: "ll25",
    homeTeam: "Atletico Madrid",
    awayTeam: "Getafe",
    date: "2024-12-15",
    time: "21:00",
    group: "Matchday 17",
    venue: "Metropolitano Stadium, Madrid",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -1.25,
    actualHomeScore: 1,
    actualAwayScore: 0,
    actualCorners: 10,
    actualCards: 4
  },
  {
    id: "ll26",
    homeTeam: "Barcelona",
    awayTeam: "Atletico Madrid",
    date: "2024-12-21",
    time: "21:00",
    group: "Matchday 18",
    venue: "Estadi Olimpic Lluis Companys, Barcelona",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -0.5,
    actualHomeScore: 2,
    actualAwayScore: 1,
    actualCorners: 11,
    actualCards: 5
  },
  {
    id: "ll27",
    homeTeam: "Real Madrid",
    awayTeam: "Sevilla",
    date: "2024-12-22",
    time: "16:15",
    group: "Matchday 18",
    venue: "Santiago Bernabeu, Madrid",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -1.5,
    actualHomeScore: 3,
    actualAwayScore: 1,
    actualCorners: 10,
    actualCards: 3
  },
  {
    id: "ll28",
    homeTeam: "Athletic Bilbao",
    awayTeam: "Real Sociedad",
    date: "2024-11-24",
    time: "21:00",
    group: "Matchday 14",
    venue: "San Mames, Bilbao",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -0.25,
    actualHomeScore: 1,
    actualAwayScore: 0,
    actualCorners: 9,
    actualCards: 5
  },
  {
    id: "ll29",
    homeTeam: "Real Sociedad",
    awayTeam: "Atletico Madrid",
    date: "2024-10-06",
    time: "21:00",
    group: "Matchday 9",
    venue: "Reale Arena, San Sebastian",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: 0.25,
    actualHomeScore: 1,
    actualAwayScore: 1,
    actualCorners: 8,
    actualCards: 4
  },
  {
    id: "ll30",
    homeTeam: "Girona",
    awayTeam: "Athletic Bilbao",
    date: "2024-10-06",
    time: "14:00",
    group: "Matchday 9",
    venue: "Montilivi, Girona",
    tournament: "La Liga",
    season: "2024-2025",
    isTest: true,
    marketHandicap: -0.25,
    actualHomeScore: 2,
    actualAwayScore: 1,
    actualCorners: 9,
    actualCards: 5
  }
];

function appendFixtures() {
  if (!fs.existsSync(fixturesPath)) {
    console.error('❌ Không tìm thấy fixtures.json');
    return;
  }
  
  const data = JSON.parse(fs.readFileSync(fixturesPath, 'utf8'));
  
  // Tránh trùng lặp ID
  const existingIds = new Set(data.fixtures.map(f => f.id));
  const toAdd = newFixtures.filter(f => !existingIds.has(f.id));
  
  data.fixtures.push(...toAdd);
  
  fs.writeFileSync(fixturesPath, JSON.stringify(data, null, 2), 'utf8');
  console.log(`✅ Đã nạp thêm ${toAdd.length} trận đấu mới vào fixtures.json.`);
}

appendFixtures();
